### ISSUE TITLE
UI: variable never initialised lead to NPE

### ISSUE THREAD

**Issue by slux83** [dariol83/reatmetric#5]
Hi,

I noticed that the variable `eu.dariolucia.reatmetric.ui.controller.MainViewController#modelController` is never initialised nor linked to an object in the FXML. 

this variable is only accessed by the `eu.dariolucia.reatmetric.ui.controller.MainViewController.Facade#getModelController()` which is accessed by the following 
`eu.dariolucia.reatmetric.ui.controller.AckMessageDialogController#dataItemsReceived(...)`
`eu.dariolucia.reatmetric.ui.controller.MimicsSvgViewController.JSBinding#exec(...)`
`eu.dariolucia.reatmetric.ui.controller.MimicsSvgViewController.JSBinding#set(...)`

I noticed this because I got a NPE at startup:
```
java.lang.NullPointerException
	at xxxx.AckMessageDialogController.lambda$dataItemsReceived$9(AckMessageDialogController.java:207)
	at xxxx.ui.utils.FxUtils.lambda$runLater$0(FxUtils.java:26)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

It could be very likely this is an issue caused by my changes. :) In that case, feel free to discard this

**Comment by dariol83** [comment]
I think it is due to your modifications. If the view is included in a FXML file via fx:include, then the controller of such view can be set in the parent controller by naming convention. See https://riptutorial.com/javafx/example/7285/nested-controllers

In my case, the field is populated as expected.
![image](https://user-images.githubusercontent.com/50966020/106776946-d3abe800-6644-11eb-8156-eac14ca2f42a.png)
